### ISSUE TITLE
Ordering issue

### ISSUE THREAD

**Issue by ddeboer** [editorconfig/editorconfig-jetbrains#40] opened 2014-05-07 07:48 UTC
With the following `.editorconfig` YML files are incorrectly indented with 4 spaces

``` ini
root = true

[*]
indent_size = 4

[*.yml]
indent_size = 2
```

While with this config YMLs are correctly indented with 2 spaces:

``` ini
root = true

[*.yml]
indent_size = 2

[*]
indent_size = 4
```

So it seems the order matters. I'm not sure whether it should, as I can't find anything about this on the [EditorConfig website](http://editorconfig.org/). I think, however, my first example resembles those on the website most closely and should work as is.

**Comment by denofevil** [comment] 2014-05-07 07:52
This issue was caused by new parser incorrectly merging keys in one file and is fixed by https://github.com/editorconfig/editorconfig-core-java/commit/c1c249a8670c004999333f9d5573dfb2e869f110, we will post updated plugin version soon

**Comment by ddeboer** [comment] 2014-05-07 07:52
Very cool! Thanks for the great plugin, by the way. :smile:

**Closed as completed by denofevil** 2014-05-07 07:52 UTC
