### ISSUE TITLE
PhpStorm not respecting some settings when editorconfig plugin installed

### ISSUE THREAD

**Issue by antonymous** [editorconfig/editorconfig-jetbrains#21] opened 2013-10-02 10:51 UTC
When installed, plugin somehow prevents PhpStorm from remembering editor appearance settings "Show whitespaces" and "Show line numbers"; ~~and also from opening files as Windows-1251 (they are opened as UTF-8) despite file encodings is set to "Windows-1251" at the project level~~ (UPDATE: not relevant, uninstalled plugin and still occasionally having the issue).
Everything is back to normal when I uninstall the plugin.
Ubuntu 13.04 x86_64, Java v.7 & v.8-EA, PhpStorm is latest EA-version, build 131-205.

**Comment by kenkouot** [comment] 2013-10-31 02:50
Same as #14

**Comment by bellkev** [comment] 2013-12-18 02:23
Closed as duplicate of #14

**Closed as completed by bellkev** 2013-12-18 02:23 UTC
