### ISSUE TITLE
Plugin resets editor settings in WebStorm to defaults

### ISSUE THREAD

**Issue by nDmitry** [editorconfig/editorconfig-jetbrains#14] opened 2013-08-13 09:49 UTC
Plugin resets not only configurable via .editorconfig file settings, but _all_ editor settings in WebStorm 6.0.2 to defaults. So you just can't use soft wraps or disable placement of caret after end of line.

**Comment by bellkev** [comment] 2013-08-15 04:17
Hi Dimitry,

I tried opening a project with .editorconfig settings in effect, turning soft wraps on/off and the caret placement option on/off and things seemed to work okay. This was with WebStorm 7 EAP.

I will try again this weekend with WS 6. In the meantime, it may help if you can provide specific steps to reproduce the error. Also, please check that you are using the latest release of EditorConfig (currently 0.1.3).

**Comment by nDmitry** [comment] 2013-08-15 05:27
Version 0.1.3 from JetBrains repository. After plugin installation I can edit editor settings and it seems ok, but when I restart IDE, the settings are reset to default again and so on.

**Comment by bellkev** [comment] 2013-08-17 04:32
Okay, I have reproduced this issue (when restarting WS as you described), and I will try to work on it this weekend or next.

**Comment by bellkev** [comment] 2013-08-19 04:38
I see what the cause of the problem is now. It's related to how I overrode a core JetBrains class (EditorSettingsExternalizable) to subscribe to changes in Editor Settings so that the appropriate settings are applied to non-editorconfig-managed files. That class is responsible for persisting "Editor" settings, and the way I am overriding it is causing the settings to be reset to defaults at startup. Really, I shouldn't be overriding the core class in the first place, and I think I know a way to fix the problem. I will try to get to it in the next week or two.

Unfortunately, for now the only workaround is to re-apply your preferred settings after WebStorm has launched.

**Comment by idris** [comment] 2013-09-05 13:43
+1 this issue exists in IntelliJ IDEA as well.

**Comment by antonfrolovsky** [comment] 2013-10-21 11:46
In progress?

**Comment by kenkouot** [comment] 2013-10-25 21:45
:+1: Webstorm too! @lizlux

**Comment by kflorence** [comment] 2013-10-25 22:50
+1 PHPStorm editor

**Comment by skrichten** [comment] 2013-10-28 14:39
I think I am having this problem as well.  My line numbers keep disappearing and its driving me mad!  WebStorm 7

**Comment by bellkev** [comment] 2013-10-30 08:07
Hey folks. Sorry for the delay in resolving this issue. It definitely appears to be the most common problem with the plugin. For everyone's information, the problem here is that in order apply the correct behavior for files that are NOT managed by .editorconfig settings, my "EditorSettingsManager" class needs keep track of the normal editor settings for stripping trailing whitespace and ensuring there is a final newline. Unfortunately, the JetBrains "EditorSettings" class does not actually fire property change events for changes to these settings (some property change-related code seems to be lying dormant in the class...) so I don't have a good way of knowing when these settings change. I tried to provide an alternative implementation with "ReplacementEditorSettingsExternalizable", but registering my alternative implementation through picocontainer is clobbering all of the saved preferences (including soft wraps, caret placement, etc...)

I wanted to fix this sooner, but due to business at my day job, I won't be able to get to it until at least December. Until then, I welcome any pull requests to fix the issue.

**Comment by brugnara** [comment] 2013-12-16 11:56
+1, phpstorm 7.1 EAP.

**Comment by bellkev** [comment] 2013-12-18 02:24
This should be fixed in 0.2.0. Please see the release notes for more info.

**Closed as completed by bellkev** 2013-12-18 02:24 UTC
